build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.19
  amd64: ghcr.io/home-assistant/amd64-base:3.19

labels:
  org.opencontainers.image.title: "Home Assistant Add-on: OpenCode"
  org.opencontainers.image.description: "Web interface for OpenCode"
  org.opencontainers.image.source: "https://github.com/anomalyco/opencode"
  org.opencontainers.image.licenses: "MIT"
